In [2]:
#import numpy

import numpy as np

In [2]:
#create simple using list

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
#dimention of array

print(arr.ndim)

2


In [7]:
#shape of array

print(arr.shape)

(2, 4)


In [9]:
#data type

print(type(arr))

<class 'numpy.ndarray'>


In [10]:
print(arr.data)

# Statistical Functions

In [14]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b
print(b,"\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



In [16]:
b.dtype

dtype('int32')

In [17]:
b.itemsize

4

In [18]:
b.size

12

In [19]:
b.shape

(3, 4)

In [3]:
b = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.float64)
print(b,"\n")
print(b.dtype,"\n")
print(b.itemsize,"\n")

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

float64 

8 



In [4]:
z = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.complex64)
print(z,"\n")
print(z.dtype,"\n")
print(z.itemsize,"\n")

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex64 

8 



In [5]:
t = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.float64)
print(t,"\n")
print(t.dtype,"\n")
print(t.itemsize,"\n")

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

float64 

8 



# stacking

In [3]:
d=np.arange(12).reshape(3,4)
print(d,"\n")
f=np.arange(12).reshape(3,4)
print(f,"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



In [7]:
d=np.arange(12).reshape(3,4)
print(d,"\n")
f=np.arange(12).reshape(3,4)
print(f,"\n")
print(np.hstack((d,f)),'\n')
print(np.hstack((f,d)),'\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]] 

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]] 



In [6]:
d=np.arange(12).reshape(3,4)
print(d,"\n")
f=np.arange(12).reshape(3,4)
print(f,"\n")
print(np.vstack((d,f)),'\n')
print(np.vstack((f,d)),'\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



# mathematical operation

In [8]:
x=np.array([2,8,10,35,55,60])
y=np.array([2,8,10,35,55,60])
print(x,"\n")
print(y,"\n")
print(x+y,"\n")
print(x-y,"\n")
print(x*y,"\n")
print(x/y,"\n")
print(x//y,"\n")

[ 2  8 10 35 55 60] 

[ 2  8 10 35 55 60] 

[  4  16  20  70 110 120] 

[0 0 0 0 0 0] 

[   4   64  100 1225 3025 3600] 

[1. 1. 1. 1. 1. 1.] 

[1 1 1 1 1 1] 



In [10]:
print(np.zeros((4,3)),"\n")
print(np.ones((4,3)),"\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 



# randon number generatoer using numpy

In [13]:
from numpy import random
x=random.randint(100)
print(x)

92


In [17]:
#generating random float

x=random.rand(10)
print(x)

[0.4607498  0.03727833 0.89250727 0.67260407 0.41149458 0.5771799
 0.69713823 0.33506373 0.25642563 0.14959942]


In [18]:
#generating radon array

x=random.randint(100,size=(15))
print(x)

[51 67 77 45 65  4  1 22  2 33 18 50 61  0 26]


# 2.4 practical : creating scalers in numpy

In [20]:
import numpy as np

in_arr=np.array([8])

print("input array is ",in_arr )
          
out_scaler=np.asscalar(in_arr)
print("output scaler from input array ",out_scaler)

input array is  [8]
output scaler from input array  8


C:\Users\Sap\AppData\Local\Temp/ipykernel_3196/131558040.py:7: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out_scaler=np.asscalar(in_arr)


# vector in numpy

In [25]:
import numpy as np

list1=[1,2,3]

list2=[[10],
       [20],
       [30]]

vector1=np.array(list1)
vector2=np.array(list2)

print("Horizontal vector")
print(vector1)

print("------------")

print("Vertical vector")
print(vector2)

Horizontal vector
[1 2 3]
------------
Vertical vector
[[10]
 [20]
 [30]]


# matrix in numpy

In [27]:
import numpy as np

a=np.matrix('1 2; 3 4')
print("via string input : \n",a,"\n\n")

b=np.matrix([[5,6,7],[4,6]])
print("via array-like input : \n",b)


via string input : 
 [[1 2]
 [3 4]] 


via array-like input : 
 [[list([5, 6, 7]) list([4, 6])]]


# matrix multiplication

In [28]:
import numpy as np

A=5
B=[[6,7],
   [8,9]]

print(np.dot(A,B))

[[30 35]
 [40 45]]


In [29]:
A=[[6,7],
   [8,9]]

B=[[1,2],
   [3,4]]

print(np.dot(A,B))

print("-------------")

[[27 40]
 [35 52]]
-------------


# IQR

In [30]:
data=[32,36,46,56,69,75,88,89,91,92,93,96,97,101,105,112,116]
#q1
q1=np.median(data[:10])
#q3
q3=np.median(data[10:])


iqr=q3-q1

print(iqr)

29.0


# array broadcasting

In [31]:
a=np.array([1.0,2.0,3.0])
b=np.array([2.0,2.0,2.0])

a*b

array([2., 4., 6.])

In [32]:
a=np.array([1.0,2.0,3.0])
b=2.0

a*b

array([2., 4., 6.])